-- 업무 화면(/app/** 등)용 테이블 — Falcon UI 목록·상세와 1:1 대응
-- USE spring_boot_app;

-- ========== E-Commerce ==========
CREATE TABLE IF NOT EXISTS ecm_product (
  product_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  company_id     BIGINT        NULL,
  product_nm     VARCHAR(200)  NOT NULL,
  category_cd    VARCHAR(50)   NULL,
  price          DECIMAL(12,2) NOT NULL DEFAULT 0,
  stock_qty      INTEGER       NOT NULL DEFAULT 0,
  status_cd      VARCHAR(30)   NOT NULL DEFAULT 'ACTIVE',
  img_url        VARCHAR(500)  NULL,
  description    TEXT          NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id      VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (product_id),
  CONSTRAINT fk_ecm_product_company FOREIGN KEY (company_id) REFERENCES biz_company (company_id)
);
CREATE INDEX IF NOT EXISTS idx_ecm_product_category ON ecm_product (category_cd);
CREATE INDEX IF NOT EXISTS idx_ecm_product_status ON ecm_product (status_cd);
CREATE INDEX IF NOT EXISTS idx_ecm_product_company ON ecm_product (company_id);

CREATE TABLE IF NOT EXISTS ecm_product_image (
  image_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  product_id   BIGINT        NOT NULL,
  sort_ord     INTEGER       NOT NULL DEFAULT 1,
  img_url      VARCHAR(500)  NOT NULL,
  reg_id       VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (image_id),
  CONSTRAINT uk_ecm_product_image_ord UNIQUE (product_id, sort_ord),
  CONSTRAINT fk_ecm_product_image_product
    FOREIGN KEY (product_id) REFERENCES ecm_product (product_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ecm_product_image_product ON ecm_product_image (product_id);

CREATE TABLE IF NOT EXISTS ecm_customer (
  customer_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  customer_nm    VARCHAR(100)  NOT NULL,
  email          VARCHAR(200)  NOT NULL,
  phone          VARCHAR(30)   NULL,
  zipcode        VARCHAR(10)   NULL,
  address        VARCHAR(255)  NULL,
  address_detail VARCHAR(255)  NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id      VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (customer_id),
  CONSTRAINT uk_ecm_customer_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS ecm_order (
  order_id         BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  order_no         VARCHAR(30)   NOT NULL,
  customer_id      BIGINT        NOT NULL,
  order_dt         DATE          NOT NULL,
  ship_to          VARCHAR(500)  NOT NULL,
  shipping_method  VARCHAR(100)  NULL,
  status_cd        VARCHAR(30)   NOT NULL,
  amount           DECIMAL(12,2) NOT NULL DEFAULT 0,
  reg_id           VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id        VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (order_id),
  CONSTRAINT uk_ecm_order_no UNIQUE (order_no),
  CONSTRAINT fk_ecm_order_customer FOREIGN KEY (customer_id) REFERENCES ecm_customer (customer_id)
);
CREATE INDEX IF NOT EXISTS idx_ecm_order_customer ON ecm_order (customer_id);
CREATE INDEX IF NOT EXISTS idx_ecm_order_status ON ecm_order (status_cd);

CREATE TABLE IF NOT EXISTS ecm_order_item (
  order_id       BIGINT        NOT NULL,
  line_no        INTEGER       NOT NULL,
  product_id     BIGINT        NOT NULL,
  qty            INTEGER       NOT NULL DEFAULT 1,
  unit_price     DECIMAL(12,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (order_id, line_no),
  CONSTRAINT fk_ecm_order_item_order FOREIGN KEY (order_id) REFERENCES ecm_order (order_id) ON DELETE CASCADE,
  CONSTRAINT fk_ecm_order_item_product FOREIGN KEY (product_id) REFERENCES ecm_product (product_id)
);

CREATE TABLE IF NOT EXISTS ecm_cart_item (
  cart_item_id   BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  session_id     VARCHAR(100)  NOT NULL,
  product_id     BIGINT        NOT NULL,
  qty            INTEGER       NOT NULL DEFAULT 1,
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (cart_item_id),
  CONSTRAINT fk_ecm_cart_product FOREIGN KEY (product_id) REFERENCES ecm_product (product_id)
);
CREATE INDEX IF NOT EXISTS idx_ecm_cart_session ON ecm_cart_item (session_id);

CREATE TABLE IF NOT EXISTS ecm_invoice (
  invoice_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  order_id       BIGINT        NOT NULL,
  invoice_no     VARCHAR(30)   NOT NULL,
  issue_dt       DATE          NOT NULL,
  total_amount   DECIMAL(12,2) NOT NULL DEFAULT 0,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (invoice_id),
  CONSTRAINT uk_ecm_invoice_no UNIQUE (invoice_no),
  CONSTRAINT fk_ecm_invoice_order FOREIGN KEY (order_id) REFERENCES ecm_order (order_id)
);

CREATE TABLE IF NOT EXISTS ecm_billing (
  billing_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  customer_id    BIGINT        NOT NULL,
  cycle_cd       VARCHAR(30)   NOT NULL,
  plan_nm        VARCHAR(100)  NOT NULL,
  amount         DECIMAL(12,2) NOT NULL DEFAULT 0,
  next_bill_dt   DATE          NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (billing_id),
  CONSTRAINT fk_ecm_billing_customer FOREIGN KEY (customer_id) REFERENCES ecm_customer (customer_id)
);

-- ========== E-Learning ==========
CREATE TABLE IF NOT EXISTS lms_course (
  course_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  course_nm      VARCHAR(200)  NOT NULL,
  category_cd    VARCHAR(50)   NULL,
  trainer_nm     VARCHAR(100)  NULL,
  price          DECIMAL(12,2) NOT NULL DEFAULT 0,
  rating         DECIMAL(3,2)  NULL,
  feature_cd     VARCHAR(50)   NULL,
  status_cd      VARCHAR(30)   NOT NULL DEFAULT 'OPEN',
  description    TEXT          NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id      VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS lms_enrollment (
  enrollment_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  course_id      BIGINT        NOT NULL,
  student_nm     VARCHAR(100)  NOT NULL,
  progress_pct   INTEGER       NOT NULL DEFAULT 0,
  enrolled_dt    DATE          NOT NULL,
  PRIMARY KEY (enrollment_id),
  CONSTRAINT fk_lms_enrollment_course FOREIGN KEY (course_id) REFERENCES lms_course (course_id)
);

CREATE TABLE IF NOT EXISTS lms_trainer (
  trainer_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  trainer_nm     VARCHAR(100)  NOT NULL,
  email          VARCHAR(200)  NULL,
  bio            TEXT          NULL,
  avatar_url     VARCHAR(500)  NULL,
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (trainer_id)
);

-- ========== Email ==========
CREATE TABLE IF NOT EXISTS email_message (
  message_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  folder_cd      VARCHAR(20)   NOT NULL DEFAULT 'INBOX',
  subject        VARCHAR(500)  NOT NULL,
  sender_email   VARCHAR(200)  NOT NULL,
  recipient      VARCHAR(500)  NOT NULL,
  body_text      TEXT          NULL,
  read_yn        CHAR(1)       NOT NULL DEFAULT 'N',
  starred_yn     CHAR(1)       NOT NULL DEFAULT 'N',
  sent_dt        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (message_id)
);
CREATE INDEX IF NOT EXISTS idx_email_folder ON email_message (folder_cd);
CREATE INDEX IF NOT EXISTS idx_email_sent ON email_message (sent_dt);

-- ========== Calendar / Events ==========
CREATE TABLE IF NOT EXISTS calendar_event (
  event_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  title          VARCHAR(200)  NOT NULL,
  category_cd    VARCHAR(50)   NULL,
  label_cd       VARCHAR(50)   NULL,
  start_dt       TIMESTAMP     NOT NULL,
  end_dt         TIMESTAMP     NULL,
  location       VARCHAR(255)  NULL,
  description    TEXT          NULL,
  all_day_yn     CHAR(1)       NOT NULL DEFAULT 'N',
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id      VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (event_id)
);
CREATE INDEX IF NOT EXISTS idx_calendar_event_start ON calendar_event (start_dt);

-- ========== Social ==========
CREATE TABLE IF NOT EXISTS social_post (
  post_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  author_nm      VARCHAR(100)  NOT NULL,
  content        TEXT          NOT NULL,
  like_cnt       INTEGER       NOT NULL DEFAULT 0,
  comment_cnt    INTEGER       NOT NULL DEFAULT 0,
  posted_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS social_activity (
  activity_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  actor_nm       VARCHAR(100)  NOT NULL,
  action_cd      VARCHAR(50)   NOT NULL,
  target_desc    VARCHAR(500)  NULL,
  activity_dt    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (activity_id)
);

CREATE TABLE IF NOT EXISTS social_notification (
  notification_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  user_nm        VARCHAR(100)  NOT NULL,
  sender_nm      VARCHAR(100)  NULL,
  message        VARCHAR(500)  NOT NULL,
  section_cd     VARCHAR(20)   NULL DEFAULT 'NEW',
  time_icon      VARCHAR(30)   NULL,
  read_yn        CHAR(1)       NOT NULL DEFAULT 'N',
  notified_dt    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (notification_id)
);
CREATE INDEX IF NOT EXISTS idx_social_notification_user ON social_notification (user_nm, notified_dt);

CREATE TABLE IF NOT EXISTS social_follower (
  follower_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  user_nm        VARCHAR(100)  NOT NULL,
  follower_nm    VARCHAR(100)  NOT NULL,
  group_cd       VARCHAR(50)   NULL,
  followed_dt    DATE          NOT NULL,
  PRIMARY KEY (follower_id)
);

-- ========== Kanban / Chat ==========
CREATE TABLE IF NOT EXISTS kanban_board (
  board_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  board_nm       VARCHAR(100)  NOT NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (board_id)
);

CREATE TABLE IF NOT EXISTS kanban_column (
  column_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  board_id       BIGINT        NOT NULL,
  column_nm      VARCHAR(100)  NOT NULL,
  sort_ord       INTEGER       NOT NULL DEFAULT 0,
  PRIMARY KEY (column_id),
  CONSTRAINT fk_kanban_column_board FOREIGN KEY (board_id) REFERENCES kanban_board (board_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS kanban_card (
  card_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  column_id      BIGINT        NOT NULL,
  title          VARCHAR(200)  NOT NULL,
  assignee_nm    VARCHAR(100)  NULL,
  due_dt         DATE          NULL,
  sort_ord       INTEGER       NOT NULL DEFAULT 0,
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (card_id),
  CONSTRAINT fk_kanban_card_column FOREIGN KEY (column_id) REFERENCES kanban_column (column_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat_room (
  room_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  room_nm        VARCHAR(100)  NOT NULL,
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS chat_message (
  message_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  room_id        BIGINT        NOT NULL,
  sender_nm      VARCHAR(100)  NOT NULL,
  body_text      TEXT          NOT NULL,
  sent_dt        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (message_id),
  CONSTRAINT fk_chat_message_room FOREIGN KEY (room_id) REFERENCES chat_room (room_id) ON DELETE CASCADE
);

-- ========== Pages (Pricing / FAQ) ==========
CREATE TABLE IF NOT EXISTS pricing_plan (
  plan_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  plan_nm        VARCHAR(100)  NOT NULL,
  price_monthly  DECIMAL(12,2) NOT NULL DEFAULT 0,
  price_yearly   DECIMAL(12,2) NULL,
  feature_json   JSON          NULL,
  sort_ord       INTEGER       NOT NULL DEFAULT 0,
  use_yn         CHAR(1)       NOT NULL DEFAULT 'Y',
  PRIMARY KEY (plan_id)
);

CREATE TABLE IF NOT EXISTS faq_item (
  faq_id         BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  category_nm    VARCHAR(100)  NULL,
  question       VARCHAR(500)  NOT NULL,
  answer         TEXT          NOT NULL,
  sort_ord       INTEGER       NOT NULL DEFAULT 0,
  use_yn         CHAR(1)       NOT NULL DEFAULT 'Y',
  PRIMARY KEY (faq_id)
);
