-- 상품 이미지 (최대 5장 / 상품)
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS ecm_product_image (
  image_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  product_id   BIGINT        NOT NULL,
  sort_ord     INTEGER       NOT NULL DEFAULT 1,
  img_url      VARCHAR(500)  NOT NULL,
  reg_id       VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (image_id),
  CONSTRAINT uk_ecm_product_image_ord UNIQUE (product_id, sort_ord),
  CONSTRAINT fk_ecm_product_image_product
    FOREIGN KEY (product_id) REFERENCES ecm_product (product_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ecm_product_image_product ON ecm_product_image (product_id);
