-- =============================================================================
-- spring_boot_app 전체 테이블 CREATE (DBeaver: 이 파일 SQL 편집기에서 전체 실행)
-- 계정: redcroxx / DB: spring_boot_app / PostgreSQL 16
-- =============================================================================

-- ########## 00_create_database.sql ##########
-- DB 생성 (root 또는 CREATE 권한 계정으로 1회 실행)
-- CREATE DATABASE IF NOT EXISTS spring_boot_app
--   CHARACTER SET utf8mb4
--   COLLATE utf8mb4_unicode_ci;

-- USE spring_boot_app;

-- ########## user.sql ##########
-- spring_boot_app.user 테이블
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS "user" (
  id        VARCHAR(100) NOT NULL,
  pw        VARCHAR(100) NOT NULL,
  name      VARCHAR(100) NOT NULL,
  sex       VARCHAR(100) NOT NULL,
  rrno      VARCHAR(255) NOT NULL,
  email          VARCHAR(100) NOT NULL,
  zipcode        VARCHAR(10) NULL,
  address        VARCHAR(255) NULL,
  address_detail VARCHAR(255) NULL,
  update_id VARCHAR(100) NOT NULL,
  reg_dt    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  upd_dt    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT user_unique UNIQUE (email)
);

-- ########## user_access_log.sql ##########
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS user_access_log (
  access_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  user_id         VARCHAR(100)  NULL,
  user_nm         VARCHAR(100)  NULL,
  access_type_cd  VARCHAR(30)   NOT NULL,
  login_type_cd   VARCHAR(30)   NULL,
  success_yn      CHAR(1)       NOT NULL DEFAULT 'Y',
  request_uri     VARCHAR(500)  NULL,
  http_method     VARCHAR(10)   NULL,
  client_ip       VARCHAR(45)   NULL,
  device_type_cd  VARCHAR(20)   NULL,
  device_os       VARCHAR(80)   NULL,
  device_browser  VARCHAR(80)   NULL,
  device_model    VARCHAR(120)  NULL,
  user_agent      VARCHAR(500)  NULL,
  session_id      VARCHAR(64)   NULL,
  fail_reason     VARCHAR(255)  NULL,
  access_dt       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reg_id          VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  PRIMARY KEY (access_id)
);
CREATE INDEX IF NOT EXISTS idx_user_access_log_user_dt ON user_access_log (user_id, access_dt);
CREATE INDEX IF NOT EXISTS idx_user_access_log_dt ON user_access_log (access_dt);
CREATE INDEX IF NOT EXISTS idx_user_access_log_type ON user_access_log (access_type_cd);

-- ########## biz_company.sql ##########
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS biz_company (
  company_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  company_nm    VARCHAR(200)  NOT NULL,
  biz_no        VARCHAR(20)   NULL,
  ceo_nm        VARCHAR(100)  NULL,
  tel           VARCHAR(30)   NULL,
  email         VARCHAR(200)  NULL,
  address       VARCHAR(500)  NULL,
  status_cd     VARCHAR(30)   NOT NULL DEFAULT 'ACTIVE',
  use_yn        CHAR(1)       NOT NULL DEFAULT 'Y',
  memo          VARCHAR(1000) NULL,
  reg_id        VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id     VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (company_id)
);
CREATE INDEX IF NOT EXISTS idx_biz_company_nm ON biz_company (company_nm);
CREATE INDEX IF NOT EXISTS idx_biz_company_status ON biz_company (status_cd);
CREATE INDEX IF NOT EXISTS idx_biz_company_use ON biz_company (use_yn);

-- ########## ecm_payment.sql ##########
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS ecm_payment (
  payment_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  order_no        VARCHAR(64)   NOT NULL,
  order_id        BIGINT        NULL,
  pg_cd           VARCHAR(20)   NOT NULL DEFAULT 'INICIS',
  mid             VARCHAR(20)   NULL,
  tid             VARCHAR(100)  NULL,
  amount          DECIMAL(12,2) NOT NULL,
  currency_cd     VARCHAR(10)   NOT NULL DEFAULT 'WON',
  good_name       VARCHAR(200)  NOT NULL,
  buyer_name      VARCHAR(100)  NULL,
  buyer_tel       VARCHAR(30)   NULL,
  buyer_email     VARCHAR(200)  NULL,
  status_cd       VARCHAR(30)   NOT NULL DEFAULT 'READY',
  result_code     VARCHAR(20)   NULL,
  result_msg      VARCHAR(500)  NULL,
  auth_token      VARCHAR(500)  NULL,
  idc_name        VARCHAR(50)   NULL,
  raw_auth_json   TEXT          NULL,
  raw_approve_json TEXT         NULL,
  reg_id          VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id       VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (payment_id),
  CONSTRAINT uk_ecm_payment_order_no UNIQUE (order_no)
);
CREATE INDEX IF NOT EXISTS idx_ecm_payment_status ON ecm_payment (status_cd);
CREATE INDEX IF NOT EXISTS idx_ecm_payment_tid ON ecm_payment (tid);

-- ########## common_code.sql ##########
-- 공통코드 마스터·상세 (신규 DB용)
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS common_code (
  code_id      VARCHAR(50)   NOT NULL,
  code_nm      VARCHAR(200)  NOT NULL,
  use_yn       CHAR(1)       NOT NULL DEFAULT 'Y',
  reg_id       VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  regdate_dt   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id    VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (code_id)
);

CREATE TABLE IF NOT EXISTS common_code_value (
  code_id      VARCHAR(50)   NOT NULL,
  code_val     VARCHAR(100)  NOT NULL,
  use_yn       CHAR(1)       NOT NULL DEFAULT 'Y',
  reg_id       VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  regdate_dt   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id    VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (code_id, code_val),
  CONSTRAINT fk_common_code_value_group
    FOREIGN KEY (code_id) REFERENCES common_code (code_id) ON DELETE CASCADE
);

-- ########## screen_list.sql ##########
-- 화면 마스터 (신규 DB용). 기존 테이블이 있으면 screen_list_alter.sql 사용
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS screen_list (
  screen_id      VARCHAR(100)  NOT NULL,
  screen_nm      VARCHAR(200)  NOT NULL,
  uri_path       VARCHAR(255)  NOT NULL,
  template_path  VARCHAR(255)  NULL,
  sort_ord       INT           NOT NULL DEFAULT 0,
  use_yn         CHAR(1)       NOT NULL DEFAULT 'Y',
  reg_id         VARCHAR(100)  NOT NULL,
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id      VARCHAR(100)  NOT NULL,
  update_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (screen_id),
  CONSTRAINT uk_screen_list_uri UNIQUE (uri_path)
);

-- ########## screen_table_map.sql ##########
-- 화면(URL)별 연동 테이블 매핑
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS screen_table_map (
  uri_path        VARCHAR(255)  NOT NULL,
  screen_id       VARCHAR(100)  NULL,
  primary_table   VARCHAR(64)   NULL,
  related_tables  VARCHAR(500)  NULL,
  data_type       CHAR(1)       NOT NULL DEFAULT 'S',
  table_desc      VARCHAR(500)  NULL,
  reg_id          VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id       VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (uri_path)
);
CREATE INDEX IF NOT EXISTS idx_screen_table_map_screen ON screen_table_map (screen_id);
CREATE INDEX IF NOT EXISTS idx_screen_table_map_primary ON screen_table_map (primary_table);

-- ########## tables\biz_schema.sql ##########
-- 업무 화면(/app/** 등)용 테이블 — Falcon UI 목록·상세와 1:1 대응
-- USE spring_boot_app;

-- ========== E-Commerce ==========
CREATE TABLE IF NOT EXISTS ecm_product (
  product_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  product_nm     VARCHAR(200)  NOT NULL,
  category_cd    VARCHAR(50)   NULL,
  price          DECIMAL(12,2) NOT NULL DEFAULT 0,
  stock_qty      INT           NOT NULL DEFAULT 0,
  status_cd      VARCHAR(30)   NOT NULL DEFAULT 'ACTIVE',
  img_url        VARCHAR(500)  NULL,
  description    TEXT          NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id      VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (product_id)
);
CREATE INDEX IF NOT EXISTS idx_ecm_product_category ON ecm_product (category_cd);
CREATE INDEX IF NOT EXISTS idx_ecm_product_status ON ecm_product (status_cd);

CREATE TABLE IF NOT EXISTS ecm_customer (
  customer_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  customer_nm    VARCHAR(100)  NOT NULL,
  email          VARCHAR(200)  NOT NULL,
  phone          VARCHAR(30)   NULL,
  zipcode        VARCHAR(10)   NULL,
  address        VARCHAR(255)  NULL,
  address_detail VARCHAR(255)  NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id      VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (customer_id),
  CONSTRAINT uk_ecm_customer_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS ecm_order (
  order_id         BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  order_no         VARCHAR(30)   NOT NULL,
  customer_id      BIGINT        NOT NULL,
  order_dt         DATE          NOT NULL,
  ship_to          VARCHAR(500)  NOT NULL,
  shipping_method  VARCHAR(100)  NULL,
  status_cd        VARCHAR(30)   NOT NULL,
  amount           DECIMAL(12,2) NOT NULL DEFAULT 0,
  reg_id           VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id        VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (order_id),
  CONSTRAINT uk_ecm_order_no UNIQUE (order_no),
  CONSTRAINT fk_ecm_order_customer FOREIGN KEY (customer_id) REFERENCES ecm_customer (customer_id)
);
CREATE INDEX IF NOT EXISTS idx_ecm_order_customer ON ecm_order (customer_id);
CREATE INDEX IF NOT EXISTS idx_ecm_order_status ON ecm_order (status_cd);

CREATE TABLE IF NOT EXISTS ecm_order_item (
  order_id       BIGINT        NOT NULL,
  line_no        INT           NOT NULL,
  product_id     BIGINT        NOT NULL,
  qty            INT           NOT NULL DEFAULT 1,
  unit_price     DECIMAL(12,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (order_id, line_no),
  CONSTRAINT fk_ecm_order_item_order FOREIGN KEY (order_id) REFERENCES ecm_order (order_id) ON DELETE CASCADE,
  CONSTRAINT fk_ecm_order_item_product FOREIGN KEY (product_id) REFERENCES ecm_product (product_id)
);

CREATE TABLE IF NOT EXISTS ecm_cart_item (
  cart_item_id   BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  session_id     VARCHAR(100)  NOT NULL,
  product_id     BIGINT        NOT NULL,
  qty            INT           NOT NULL DEFAULT 1,
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (cart_item_id),
  CONSTRAINT fk_ecm_cart_product FOREIGN KEY (product_id) REFERENCES ecm_product (product_id)
);
CREATE INDEX IF NOT EXISTS idx_ecm_cart_session ON ecm_cart_item (session_id);

CREATE TABLE IF NOT EXISTS ecm_invoice (
  invoice_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  order_id       BIGINT        NOT NULL,
  invoice_no     VARCHAR(30)   NOT NULL,
  issue_dt       DATE          NOT NULL,
  total_amount   DECIMAL(12,2) NOT NULL DEFAULT 0,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (invoice_id),
  CONSTRAINT uk_ecm_invoice_no UNIQUE (invoice_no),
  CONSTRAINT fk_ecm_invoice_order FOREIGN KEY (order_id) REFERENCES ecm_order (order_id)
);

CREATE TABLE IF NOT EXISTS ecm_billing (
  billing_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  customer_id    BIGINT        NOT NULL,
  cycle_cd       VARCHAR(30)   NOT NULL,
  plan_nm        VARCHAR(100)  NOT NULL,
  amount         DECIMAL(12,2) NOT NULL DEFAULT 0,
  next_bill_dt   DATE          NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (billing_id),
  CONSTRAINT fk_ecm_billing_customer FOREIGN KEY (customer_id) REFERENCES ecm_customer (customer_id)
);

-- ========== E-Learning ==========
CREATE TABLE IF NOT EXISTS lms_course (
  course_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  course_nm      VARCHAR(200)  NOT NULL,
  category_cd    VARCHAR(50)   NULL,
  trainer_nm     VARCHAR(100)  NULL,
  price          DECIMAL(12,2) NOT NULL DEFAULT 0,
  rating         DECIMAL(3,2)  NULL,
  feature_cd     VARCHAR(50)   NULL,
  status_cd      VARCHAR(30)   NOT NULL DEFAULT 'OPEN',
  description    TEXT          NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id      VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS lms_enrollment (
  enrollment_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  course_id      BIGINT        NOT NULL,
  student_nm     VARCHAR(100)  NOT NULL,
  progress_pct   INT           NOT NULL DEFAULT 0,
  enrolled_dt    DATE          NOT NULL,
  PRIMARY KEY (enrollment_id),
  CONSTRAINT fk_lms_enrollment_course FOREIGN KEY (course_id) REFERENCES lms_course (course_id)
);

CREATE TABLE IF NOT EXISTS lms_trainer (
  trainer_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  trainer_nm     VARCHAR(100)  NOT NULL,
  email          VARCHAR(200)  NULL,
  bio            TEXT          NULL,
  avatar_url     VARCHAR(500)  NULL,
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (trainer_id)
);

-- ========== Email ==========
CREATE TABLE IF NOT EXISTS email_message (
  message_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  folder_cd      VARCHAR(20)   NOT NULL DEFAULT 'INBOX',
  subject        VARCHAR(500)  NOT NULL,
  sender_email   VARCHAR(200)  NOT NULL,
  recipient      VARCHAR(500)  NOT NULL,
  body_text      TEXT          NULL,
  read_yn        CHAR(1)       NOT NULL DEFAULT 'N',
  starred_yn     CHAR(1)       NOT NULL DEFAULT 'N',
  sent_dt        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (message_id)
);
CREATE INDEX IF NOT EXISTS idx_email_folder ON email_message (folder_cd);
CREATE INDEX IF NOT EXISTS idx_email_sent ON email_message (sent_dt);

-- ========== Calendar / Events ==========
CREATE TABLE IF NOT EXISTS calendar_event (
  event_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  title          VARCHAR(200)  NOT NULL,
  category_cd    VARCHAR(50)   NULL,
  label_cd       VARCHAR(50)   NULL,
  start_dt       TIMESTAMP     NOT NULL,
  end_dt         TIMESTAMP     NULL,
  location       VARCHAR(255)  NULL,
  description    TEXT          NULL,
  all_day_yn     CHAR(1)       NOT NULL DEFAULT 'N',
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id      VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (event_id)
);
CREATE INDEX IF NOT EXISTS idx_calendar_event_start ON calendar_event (start_dt);

-- ========== Social ==========
CREATE TABLE IF NOT EXISTS social_post (
  post_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  author_nm      VARCHAR(100)  NOT NULL,
  content        TEXT          NOT NULL,
  like_cnt       INT           NOT NULL DEFAULT 0,
  comment_cnt    INT           NOT NULL DEFAULT 0,
  posted_dt      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS social_activity (
  activity_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  actor_nm       VARCHAR(100)  NOT NULL,
  action_cd      VARCHAR(50)   NOT NULL,
  target_desc    VARCHAR(500)  NULL,
  activity_dt    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (activity_id)
);

CREATE TABLE IF NOT EXISTS social_notification (
  notification_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  user_nm        VARCHAR(100)  NOT NULL,
  sender_nm      VARCHAR(100)  NULL,
  message        VARCHAR(500)  NOT NULL,
  section_cd     VARCHAR(20)   NULL DEFAULT 'NEW',
  time_icon      VARCHAR(30)   NULL,
  read_yn        CHAR(1)       NOT NULL DEFAULT 'N',
  notified_dt    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (notification_id)
);
CREATE INDEX IF NOT EXISTS idx_social_notification_user ON social_notification (user_nm, notified_dt);

CREATE TABLE IF NOT EXISTS social_follower (
  follower_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  user_nm        VARCHAR(100)  NOT NULL,
  follower_nm    VARCHAR(100)  NOT NULL,
  group_cd       VARCHAR(50)   NULL,
  followed_dt    DATE          NOT NULL,
  PRIMARY KEY (follower_id)
);

-- ========== Kanban / Chat ==========
CREATE TABLE IF NOT EXISTS kanban_board (
  board_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  board_nm       VARCHAR(100)  NOT NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (board_id)
);

CREATE TABLE IF NOT EXISTS kanban_column (
  column_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  board_id       BIGINT        NOT NULL,
  column_nm      VARCHAR(100)  NOT NULL,
  sort_ord       INT           NOT NULL DEFAULT 0,
  PRIMARY KEY (column_id),
  CONSTRAINT fk_kanban_column_board FOREIGN KEY (board_id) REFERENCES kanban_board (board_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS kanban_card (
  card_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  column_id      BIGINT        NOT NULL,
  title          VARCHAR(200)  NOT NULL,
  assignee_nm    VARCHAR(100)  NULL,
  due_dt         DATE          NULL,
  sort_ord       INT           NOT NULL DEFAULT 0,
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (card_id),
  CONSTRAINT fk_kanban_card_column FOREIGN KEY (column_id) REFERENCES kanban_column (column_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat_room (
  room_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  room_nm        VARCHAR(100)  NOT NULL,
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS chat_message (
  message_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  room_id        BIGINT        NOT NULL,
  sender_nm      VARCHAR(100)  NOT NULL,
  body_text      TEXT          NOT NULL,
  sent_dt        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (message_id),
  CONSTRAINT fk_chat_message_room FOREIGN KEY (room_id) REFERENCES chat_room (room_id) ON DELETE CASCADE
);

-- ========== Pages (Pricing / FAQ) ==========
CREATE TABLE IF NOT EXISTS pricing_plan (
  plan_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  plan_nm        VARCHAR(100)  NOT NULL,
  price_monthly  DECIMAL(12,2) NOT NULL DEFAULT 0,
  price_yearly   DECIMAL(12,2) NULL,
  feature_json   JSON          NULL,
  sort_ord       INT           NOT NULL DEFAULT 0,
  use_yn         CHAR(1)       NOT NULL DEFAULT 'Y',
  PRIMARY KEY (plan_id)
);

CREATE TABLE IF NOT EXISTS faq_item (
  faq_id         BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  category_nm    VARCHAR(100)  NULL,
  question       VARCHAR(500)  NOT NULL,
  answer         TEXT          NOT NULL,
  sort_ord       INT           NOT NULL DEFAULT 0,
  use_yn         CHAR(1)       NOT NULL DEFAULT 'Y',
  PRIMARY KEY (faq_id)
);
