-- 업체별 페이지 이미지 (슬롯당 1건)
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS biz_company_page_image (
  image_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  company_id    BIGINT        NOT NULL,
  page_cd       VARCHAR(50)   NOT NULL,
  nas_file_id   BIGINT        NULL,
  url_path      VARCHAR(500)  NOT NULL,
  alt_text      VARCHAR(200)  NULL,
  use_yn        CHAR(1)       NOT NULL DEFAULT 'Y',
  reg_id        VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id     VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (image_id),
  CONSTRAINT uk_company_page UNIQUE (company_id, page_cd)
);
CREATE INDEX IF NOT EXISTS idx_company_page_company ON biz_company_page_image (company_id);
CREATE INDEX IF NOT EXISTS idx_company_page_file ON biz_company_page_image (nas_file_id);
