-- 업체별 접속 도메인 등록
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS biz_company_domain (
  domain_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  company_id      BIGINT        NOT NULL,
  host_name       VARCHAR(253)  NOT NULL,
  primary_yn      CHAR(1)       NOT NULL DEFAULT 'N',
  ssl_yn          CHAR(1)       NOT NULL DEFAULT 'Y',
  ssl_cert_not_before TIMESTAMP NULL,
  ssl_cert_not_after  TIMESTAMP NULL,
  ssl_cert_subject    VARCHAR(500) NULL,
  ssl_cert_issuer     VARCHAR(500) NULL,
  ssl_cert_file_id    BIGINT    NULL,
  verify_status_cd VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
  use_yn          CHAR(1)       NOT NULL DEFAULT 'Y',
  memo            VARCHAR(500)  NULL,
  reg_id          VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id       VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (domain_id),
  CONSTRAINT uk_biz_company_domain_host UNIQUE (host_name)
);
CREATE INDEX IF NOT EXISTS idx_biz_company_domain_company ON biz_company_domain (company_id);
CREATE INDEX IF NOT EXISTS idx_biz_company_domain_use ON biz_company_domain (use_yn);
