-- 업체(거래처) 마스터 — 관리자 > 업체관리
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS biz_company (
  company_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  company_nm    VARCHAR(200)  NOT NULL,
  biz_no        VARCHAR(20)   NULL,
  ceo_nm        VARCHAR(100)  NULL,
  tel           VARCHAR(30)   NULL,
  email         VARCHAR(200)  NULL,
  address       VARCHAR(500)  NULL,
  status_cd     VARCHAR(30)   NOT NULL DEFAULT 'ACTIVE',
  use_yn        CHAR(1)       NOT NULL DEFAULT 'Y',
  memo          VARCHAR(1000) NULL,
  reg_id        VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id     VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (company_id)
);
CREATE INDEX IF NOT EXISTS idx_biz_company_nm ON biz_company (company_nm);
CREATE INDEX IF NOT EXISTS idx_biz_company_status ON biz_company (status_cd);
CREATE INDEX IF NOT EXISTS idx_biz_company_use ON biz_company (use_yn);
