-- wizard / authentication wizard form-select common codes

INSERT INTO common_code (code_id, code_nm, use_yn, reg_id, update_id) VALUES
('WIZARD_GENDER', 'Wizard-Gender', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Country-List', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', 'Birth-Month', 'Y', 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE code_nm = VALUES(code_nm), use_yn = VALUES(use_yn), update_id = VALUES(update_id);

INSERT INTO common_code_value (code_id, code_val, use_yn, reg_id, update_id) VALUES
('WIZARD_GENDER', '|Select your gender ...', 'Y', 'SYSTEM', 'SYSTEM'),
('WIZARD_GENDER', 'Male|Male', 'Y', 'SYSTEM', 'SYSTEM'),
('WIZARD_GENDER', 'Female|Female', 'Y', 'SYSTEM', 'SYSTEM'),
('WIZARD_GENDER', 'Other|Other', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '|월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '01|1월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '02|2월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '03|3월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '04|4월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '05|5월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '06|6월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '07|7월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '08|8월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '09|9월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '10|10월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '11|11월', 'Y', 'SYSTEM', 'SYSTEM'),
('BIRTH_MONTH', '12|12월', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', '|Select your country ...', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Afghanistan|Afghanistan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Albania|Albania', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Algeria|Algeria', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'American Samoa|American Samoa', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Andorra|Andorra', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Angola|Angola', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Anguilla|Anguilla', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Antarctica|Antarctica', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Antigua and Barbuda|Antigua and Barbuda', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Argentina|Argentina', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Armenia|Armenia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Aruba|Aruba', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Australia|Australia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Austria|Austria', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Azerbaijan|Azerbaijan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Bahamas|Bahamas', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Bahrain|Bahrain', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Bangladesh|Bangladesh', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Barbados|Barbados', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Belarus|Belarus', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Belgium|Belgium', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Belize|Belize', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Benin|Benin', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Bermuda|Bermuda', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Bhutan|Bhutan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Bolivia|Bolivia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Bosnia and Herzegowina|Bosnia and Herzegowina', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Botswana|Botswana', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Bouvet Island|Bouvet Island', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Brazil|Brazil', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'British Indian Ocean Territory|British Indian Ocean Territory', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Brunei Darussalam|Brunei Darussalam', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Bulgaria|Bulgaria', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Burkina Faso|Burkina Faso', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Burundi|Burundi', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Cambodia|Cambodia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Cameroon|Cameroon', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Canada|Canada', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Cape Verde|Cape Verde', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Cayman Islands|Cayman Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Central African Republic|Central African Republic', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Chad|Chad', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Chile|Chile', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'China|China', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Christmas Island|Christmas Island', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Cocos (Keeling) Islands|Cocos (Keeling) Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Colombia|Colombia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Comoros|Comoros', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Congo|Congo', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Congo, the Democratic Republic of the|Congo, the Democratic Republic of the', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Cook Islands|Cook Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Costa Rica|Costa Rica', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Cote d''Ivoire|Cote d''Ivoire', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Croatia (Hrvatska)|Croatia (Hrvatska)', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Cuba|Cuba', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Cyprus|Cyprus', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Czech Republic|Czech Republic', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Denmark|Denmark', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Djibouti|Djibouti', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Dominica|Dominica', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Dominican Republic|Dominican Republic', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'East Timor|East Timor', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Ecuador|Ecuador', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Egypt|Egypt', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'El Salvador|El Salvador', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Equatorial Guinea|Equatorial Guinea', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Eritrea|Eritrea', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Estonia|Estonia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Ethiopia|Ethiopia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Falkland Islands (Malvinas)|Falkland Islands (Malvinas)', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Faroe Islands|Faroe Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Fiji|Fiji', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Finland|Finland', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'France|France', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'France Metropolitan|France Metropolitan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'French Guiana|French Guiana', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'French Polynesia|French Polynesia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'French Southern Territories|French Southern Territories', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Gabon|Gabon', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Gambia|Gambia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Georgia|Georgia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Germany|Germany', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Ghana|Ghana', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Gibraltar|Gibraltar', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Greece|Greece', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Greenland|Greenland', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Grenada|Grenada', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Guadeloupe|Guadeloupe', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Guam|Guam', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Guatemala|Guatemala', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Guinea|Guinea', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Guinea-Bissau|Guinea-Bissau', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Guyana|Guyana', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Haiti|Haiti', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Heard and Mc Donald Islands|Heard and Mc Donald Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Holy See (Vatican City State)|Holy See (Vatican City State)', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Honduras|Honduras', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Hong Kong|Hong Kong', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Hungary|Hungary', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Iceland|Iceland', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'India|India', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Indonesia|Indonesia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Iran (Islamic Republic of)|Iran (Islamic Republic of)', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Iraq|Iraq', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Ireland|Ireland', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Israel|Israel', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Italy|Italy', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Jamaica|Jamaica', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Japan|Japan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Jordan|Jordan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Kazakhstan|Kazakhstan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Kenya|Kenya', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Kiribati|Kiribati', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Korea, Democratic People''s Republic of|Korea, Democratic People''s Republic of', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Korea, Republic of|Korea, Republic of', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Kuwait|Kuwait', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Kyrgyzstan|Kyrgyzstan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Lao, People''s Democratic Republic|Lao, People''s Democratic Republic', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Latvia|Latvia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Lebanon|Lebanon', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Lesotho|Lesotho', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Liberia|Liberia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Libyan Arab Jamahiriya|Libyan Arab Jamahiriya', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Liechtenstein|Liechtenstein', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Lithuania|Lithuania', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Luxembourg|Luxembourg', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Macau|Macau', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Macedonia, The Former Yugoslav Republic of|Macedonia, The Former Yugoslav Republic of', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Madagascar|Madagascar', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Malawi|Malawi', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Malaysia|Malaysia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Maldives|Maldives', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Mali|Mali', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Malta|Malta', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Marshall Islands|Marshall Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Martinique|Martinique', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Mauritania|Mauritania', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Mauritius|Mauritius', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Mayotte|Mayotte', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Mexico|Mexico', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Micronesia, Federated States of|Micronesia, Federated States of', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Moldova, Republic of|Moldova, Republic of', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Monaco|Monaco', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Mongolia|Mongolia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Montserrat|Montserrat', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Morocco|Morocco', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Mozambique|Mozambique', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Myanmar|Myanmar', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Namibia|Namibia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Nauru|Nauru', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Nepal|Nepal', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Netherlands|Netherlands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Netherlands Antilles|Netherlands Antilles', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'New Caledonia|New Caledonia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'New Zealand|New Zealand', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Nicaragua|Nicaragua', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Niger|Niger', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Nigeria|Nigeria', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Niue|Niue', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Norfolk Island|Norfolk Island', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Northern Mariana Islands|Northern Mariana Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Norway|Norway', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Oman|Oman', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Pakistan|Pakistan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Palau|Palau', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Panama|Panama', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Papua New Guinea|Papua New Guinea', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Paraguay|Paraguay', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Peru|Peru', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Philippines|Philippines', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Pitcairn|Pitcairn', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Poland|Poland', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Portugal|Portugal', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Puerto Rico|Puerto Rico', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Qatar|Qatar', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Reunion|Reunion', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Romania|Romania', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Russian Federation|Russian Federation', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Rwanda|Rwanda', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Saint Kitts and Nevis|Saint Kitts and Nevis', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Saint Lucia|Saint Lucia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Saint Vincent and the Grenadines|Saint Vincent and the Grenadines', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Samoa|Samoa', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'San Marino|San Marino', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Sao Tome and Principe|Sao Tome and Principe', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Saudi Arabia|Saudi Arabia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Senegal|Senegal', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Seychelles|Seychelles', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Sierra Leone|Sierra Leone', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Singapore|Singapore', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Slovakia (Slovak Republic)|Slovakia (Slovak Republic)', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Slovenia|Slovenia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Solomon Islands|Solomon Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Somalia|Somalia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'South Africa|South Africa', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'South Georgia and the South Sandwich Islands|South Georgia and the South Sandwich Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Spain|Spain', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Sri Lanka|Sri Lanka', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'St. Helena|St. Helena', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'St. Pierre and Miquelon|St. Pierre and Miquelon', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Sudan|Sudan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Suriname|Suriname', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Svalbard and Jan Mayen Islands|Svalbard and Jan Mayen Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Swaziland|Swaziland', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Sweden|Sweden', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Switzerland|Switzerland', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Syrian Arab Republic|Syrian Arab Republic', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Taiwan, Province of China|Taiwan, Province of China', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Tajikistan|Tajikistan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Tanzania, United Republic of|Tanzania, United Republic of', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Thailand|Thailand', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Togo|Togo', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Tokelau|Tokelau', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Tonga|Tonga', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Trinidad and Tobago|Trinidad and Tobago', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Tunisia|Tunisia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Turkey|Turkey', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Turkmenistan|Turkmenistan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Turks and Caicos Islands|Turks and Caicos Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Tuvalu|Tuvalu', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Uganda|Uganda', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Ukraine|Ukraine', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'United Arab Emirates|United Arab Emirates', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'United Kingdom|United Kingdom', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'United States|United States', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'United States Minor Outlying Islands|United States Minor Outlying Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Uruguay|Uruguay', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Uzbekistan|Uzbekistan', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Vanuatu|Vanuatu', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Venezuela|Venezuela', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Vietnam|Vietnam', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Virgin Islands (British)|Virgin Islands (British)', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Virgin Islands (U.S.)|Virgin Islands (U.S.)', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Wallis and Futuna Islands|Wallis and Futuna Islands', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Western Sahara|Western Sahara', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Yemen|Yemen', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Yugoslavia|Yugoslavia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Zambia|Zambia', 'Y', 'SYSTEM', 'SYSTEM'),
('COUNTRY_LIST', 'Zimbabwe|Zimbabwe', 'Y', 'SYSTEM', 'SYSTEM')
ON DUPLICATE KEY UPDATE use_yn = VALUES(use_yn), update_id = VALUES(update_id);
