-- 화면 콤보박스용 공통코드 (값|표시명, 값 생략 시 |표시명 만으로 빈 value)
-- PK (code_id, code_val) 필요

INSERT INTO common_code (code_id, code_nm, use_yn, reg_id, update_id) VALUES
('USE_YN_FILTER', '사용여부-조회', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION', '일괄작업', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION_KO', '일괄작업-한글', 'Y', 'SYSTEM', 'SYSTEM'),
('ROW_ACTION', '행작업', 'Y', 'SYSTEM', 'SYSTEM'),
('ORDER_STATUS_FILTER', '주문상태-필터', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_DATE_RANGE_KO', '대시보드기간-한글', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '대시보드월-한글', 'Y', 'SYSTEM', 'SYSTEM'),
('APP_DATE_RANGE_SHORT', '앱-단기기간', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', '캘린더-라벨', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_SORT', '상품정렬', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_CATEGORY', '상품카테고리', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_STATUS', '상품판매상태', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_SORT', '강의정렬', 'Y', 'SYSTEM', 'SYSTEM'),
('LIST_SORT', '목록정렬', 'Y', 'SYSTEM', 'SYSTEM'),
('PAGE_SIZE', '페이지크기', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', '이벤트카테고리', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_CATEGORY', '강의카테고리', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_FEATURE', '강의특징', 'Y', 'SYSTEM', 'SYSTEM'),
('BILLING_CYCLE', '결제주기', 'Y', 'SYSTEM', 'SYSTEM'),
('FORM_FIELD_TYPE', '폼필드유형', 'Y', 'SYSTEM', 'SYSTEM'),
('FOLLOWER_GROUP', '팔로워그룹', 'Y', 'SYSTEM', 'SYSTEM')
ON CONFLICT (code_id) DO UPDATE SET code_nm = EXCLUDED.code_nm, use_yn = EXCLUDED.use_yn, update_id = EXCLUDED.update_id;

INSERT INTO common_code_value (code_id, code_val, use_yn, reg_id, update_id) VALUES
('USE_YN_FILTER', '|전체', 'Y', 'SYSTEM', 'SYSTEM'),
('USE_YN_FILTER', 'Y|사용', 'Y', 'SYSTEM', 'SYSTEM'),
('USE_YN_FILTER', 'N|미사용', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION', '|Bulk actions', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION', 'Refund|Refund', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION', 'Delete|Delete', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION', 'Archive|Archive', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION_KO', '|일괄 작업', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION_KO', 'Refund|환불', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION_KO', 'Delete|삭제', 'Y', 'SYSTEM', 'SYSTEM'),
('BULK_ACTION_KO', 'Archive|보관', 'Y', 'SYSTEM', 'SYSTEM'),
('ROW_ACTION', '|Action', 'Y', 'SYSTEM', 'SYSTEM'),
('ROW_ACTION', 'Archive|Archive', 'Y', 'SYSTEM', 'SYSTEM'),
('ROW_ACTION', 'Delete|Delete', 'Y', 'SYSTEM', 'SYSTEM'),
('ORDER_STATUS_FILTER', '|전체', 'Y', 'SYSTEM', 'SYSTEM'),
('ORDER_STATUS_FILTER', 'Completed|Completed', 'Y', 'SYSTEM', 'SYSTEM'),
('ORDER_STATUS_FILTER', 'Processing|Processing', 'Y', 'SYSTEM', 'SYSTEM'),
('ORDER_STATUS_FILTER', 'On Hold|On Hold', 'Y', 'SYSTEM', 'SYSTEM'),
('ORDER_STATUS_FILTER', 'Pending|Pending', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_DATE_RANGE', '3months|Last 3 months', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_DATE_RANGE', '1month|Last month', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_DATE_RANGE_KO', '|최근 7일', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_DATE_RANGE_KO', '|지난달', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_DATE_RANGE_KO', '|작년', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '0|1월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '1|2월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '2|3월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '3|4월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '4|5월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '5|6월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '6|7월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '7|8월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '8|9월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '9|10월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '10|11월', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_MONTH_KO', '11|12월', 'Y', 'SYSTEM', 'SYSTEM'),
('APP_DATE_RANGE_SHORT', 'today|Today', 'Y', 'SYSTEM', 'SYSTEM'),
('APP_DATE_RANGE_SHORT', 'week|last week', 'Y', 'SYSTEM', 'SYSTEM'),
('APP_DATE_RANGE_SHORT', 'month|last month', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', '|없음', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', 'primary|업무', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', 'danger|중요', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', 'success|개인', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', 'warning|필수 참석', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', '|None', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', 'primary|Business', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', 'danger|Important', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', 'success|Personal', 'Y', 'SYSTEM', 'SYSTEM'),
('CALENDAR_EVENT_LABEL', 'warning|Must Attend', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_SORT', '|Best Match', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_SORT', 'newest|Newest', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_SORT', 'price|Price', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_CATEGORY', '|카테고리 선택', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_CATEGORY', 'WEARABLE|웨어러블', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_CATEGORY', 'MOBILE|모바일', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_CATEGORY', 'TABLET|태블릿', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_CATEGORY', 'COMPUTER|컴퓨터', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_CATEGORY', 'ACCESSORY|액세서리', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_CATEGORY', 'OTHER|기타', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_STATUS', '|상태 선택', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_STATUS', 'ACTIVE|판매중', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_STATUS', 'NEW|신규', 'Y', 'SYSTEM', 'SYSTEM'),
('PRODUCT_STATUS', 'INACTIVE|판매중지', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_SORT', 'rating|Rating', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_SORT', 'review|Review', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_SORT', 'price|Price', 'Y', 'SYSTEM', 'SYSTEM'),
('LIST_SORT', '|Sort by', 'Y', 'SYSTEM', 'SYSTEM'),
('LIST_SORT', 'oldest|Oldest', 'Y', 'SYSTEM', 'SYSTEM'),
('LIST_SORT', 'newest|Newest', 'Y', 'SYSTEM', 'SYSTEM'),
('LIST_SORT', 'name|Name', 'Y', 'SYSTEM', 'SYSTEM'),
('PAGE_SIZE', '9|9', 'Y', 'SYSTEM', 'SYSTEM'),
('PAGE_SIZE', '20|20', 'Y', 'SYSTEM', 'SYSTEM'),
('PAGE_SIZE', '50|50', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', '|Select Category', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'HEALTH|Health & Wellness', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'BUSINESS|Business & Professional', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'ARTS|Performing & Visual Arts', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'SCIENCE|Science & Technology', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'SPORTS|Sports & Fitness', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'CHARITY|Charity & Causes', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'FILM|Film & Media', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'FASHION|Fashion & Beauty', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'TRAVEL|Travel & Outdoor', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'ENTERTAINMENT|Entertainment', 'Y', 'SYSTEM', 'SYSTEM'),
('EVENT_CATEGORY', 'OTHER|Other', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_CATEGORY', '|Select a category', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_CATEGORY', 'CLASS|Class, Training, or Workshop', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_CATEGORY', 'CONCERT|Concert or Performance', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_CATEGORY', 'CONFERENCE|Conference', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_CATEGORY', 'CONVENTION|Convention', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_CATEGORY', 'DINNER|Dinner or Gala', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_CATEGORY', 'FESTIVAL|Festival or Fair', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_FEATURE', '|Select multiple features...', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_FEATURE', 'VIDEO_13H|Total 13 hours of video lectures', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_FEATURE', 'ARTICLE_12|12 premium article access', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_FEATURE', 'DOWNLOAD_11|11 downloadable resources', 'Y', 'SYSTEM', 'SYSTEM'),
('COURSE_FEATURE', 'MULTI_DEVICE|Mobile, Tab or TV friendly content', 'Y', 'SYSTEM', 'SYSTEM'),
('BILLING_CYCLE', '|Monthly Plan', 'Y', 'SYSTEM', 'SYSTEM'),
('BILLING_CYCLE', '1|Annual Plan', 'Y', 'SYSTEM', 'SYSTEM'),
('FORM_FIELD_TYPE', '|Select a type', 'Y', 'SYSTEM', 'SYSTEM'),
('FORM_FIELD_TYPE', 'TEXT|Text', 'Y', 'SYSTEM', 'SYSTEM'),
('FORM_FIELD_TYPE', 'CHECKBOX|Checkboxes', 'Y', 'SYSTEM', 'SYSTEM'),
('FORM_FIELD_TYPE', 'RADIO|Radio Buttons', 'Y', 'SYSTEM', 'SYSTEM'),
('FORM_FIELD_TYPE', 'TEXTAREA|Textarea', 'Y', 'SYSTEM', 'SYSTEM'),
('FORM_FIELD_TYPE', 'DATE|Date', 'Y', 'SYSTEM', 'SYSTEM'),
('FORM_FIELD_TYPE', 'DROPDOWN|Dropdowns', 'Y', 'SYSTEM', 'SYSTEM'),
('FOLLOWER_GROUP', '|All followers', 'Y', 'SYSTEM', 'SYSTEM'),
('FOLLOWER_GROUP', 'CHOIR|Concert Choir', 'Y', 'SYSTEM', 'SYSTEM'),
('FOLLOWER_GROUP', 'CHEM|Clubchem', 'Y', 'SYSTEM', 'SYSTEM'),
('FOLLOWER_GROUP', 'ART|Crafting Club', 'Y', 'SYSTEM', 'SYSTEM'),
('FOLLOWER_GROUP', 'DEBATE|Debate', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_BANDWIDTH_PERIOD', '|Last 6 Months', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_BANDWIDTH_PERIOD', '|Last Year', 'Y', 'SYSTEM', 'SYSTEM'),
('DASHBOARD_BANDWIDTH_PERIOD', '|Last 2 Year', 'Y', 'SYSTEM', 'SYSTEM')
ON CONFLICT (code_id, code_val) DO UPDATE SET use_yn = EXCLUDED.use_yn, update_id = EXCLUDED.update_id;
