-- 배송·운송장 (CJ / 우체국 / 롯데)
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS ecm_shipment (
  shipment_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  order_id          BIGINT        NOT NULL,
  carrier_cd        VARCHAR(20)   NOT NULL,
  invoice_no        VARCHAR(30)   NULL,
  status_cd         VARCHAR(20)   NOT NULL DEFAULT 'REQUESTED',
  recipient_nm      VARCHAR(100)  NOT NULL,
  recipient_phone   VARCHAR(30)   NOT NULL,
  zipcode           VARCHAR(10)   NOT NULL,
  address           VARCHAR(255)  NOT NULL,
  address_detail    VARCHAR(255)  NULL,
  box_cnt           INTEGER       NOT NULL DEFAULT 1,
  weight_kg         DECIMAL(6,2)  NULL,
  request_payload   TEXT          NULL,
  response_payload  TEXT          NULL,
  issued_dt         TIMESTAMP     NULL,
  reg_id            VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (shipment_id),
  CONSTRAINT uk_shipment_invoice UNIQUE (carrier_cd, invoice_no),
  CONSTRAINT fk_ecm_shipment_order FOREIGN KEY (order_id) REFERENCES ecm_order (order_id)
);
CREATE INDEX IF NOT EXISTS idx_shipment_order ON ecm_shipment (order_id);
CREATE INDEX IF NOT EXISTS idx_shipment_carrier ON ecm_shipment (carrier_cd, status_cd);
