-- 이니시스 등 PG 결제 이력
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS ecm_payment (
  payment_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  order_no        VARCHAR(64)   NOT NULL,
  order_id        BIGINT        NULL,
  pg_cd           VARCHAR(20)   NOT NULL DEFAULT 'INICIS',
  mid             VARCHAR(20)   NULL,
  tid             VARCHAR(100)  NULL,
  amount          DECIMAL(12,2) NOT NULL,
  currency_cd     VARCHAR(10)   NOT NULL DEFAULT 'WON',
  good_name       VARCHAR(200)  NOT NULL,
  buyer_name      VARCHAR(100)  NULL,
  buyer_tel       VARCHAR(30)   NULL,
  buyer_email     VARCHAR(200)  NULL,
  status_cd       VARCHAR(30)   NOT NULL DEFAULT 'READY',
  result_code     VARCHAR(20)   NULL,
  result_msg      VARCHAR(500)  NULL,
  auth_token      VARCHAR(500)  NULL,
  idc_name        VARCHAR(50)   NULL,
  raw_auth_json   TEXT          NULL,
  raw_approve_json TEXT         NULL,
  reg_id          VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_id       VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  update_dt       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (payment_id),
  CONSTRAINT uk_ecm_payment_order_no UNIQUE (order_no)
);
CREATE INDEX IF NOT EXISTS idx_ecm_payment_status ON ecm_payment (status_cd);
CREATE INDEX IF NOT EXISTS idx_ecm_payment_tid ON ecm_payment (tid);
