-- NAS 저장 파일 메타 (이미지·문서·영상·상품)
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS nas_file (
  file_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  media_type_cd  VARCHAR(20)   NOT NULL,
  stored_nm      VARCHAR(255)  NOT NULL,
  original_nm    VARCHAR(500)  NULL,
  file_ext       VARCHAR(20)   NULL,
  file_size      BIGINT        NOT NULL DEFAULT 0,
  file_path      VARCHAR(1000) NOT NULL,
  url_path       VARCHAR(500)  NOT NULL,
  content_type   VARCHAR(100)  NULL,
  reg_id         VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  reg_dt         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (file_id)
);
CREATE INDEX IF NOT EXISTS idx_nas_file_type_dt ON nas_file (media_type_cd, reg_dt);
CREATE INDEX IF NOT EXISTS idx_nas_file_url ON nas_file (url_path);
