-- PostgreSQL은 USE 미지원 — 접속 시 DB가 지정됨
-- USE spring_boot_app;
ALTER TABLE "user" DROP COLUMN IF EXISTS "????";
-- PostgreSQL은 컬럼 위치 지정(AFTER) 미지원 — AFTER 절 제거
ALTER TABLE "user"
  ADD COLUMN IF NOT EXISTS reg_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS upd_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
