USE spring_boot_app;

ALTER TABLE `user` DROP COLUMN `????`;

ALTER TABLE `user`
  ADD COLUMN `reg_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'registration datetime' AFTER `update_id`,
  ADD COLUMN `upd_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update datetime' AFTER `reg_dt`;
