-- 사용자 접속(로그인·로그아웃·화면) 이력
-- USE spring_boot_app;

CREATE TABLE IF NOT EXISTS user_access_log (
  access_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  user_id         VARCHAR(100)  NULL,
  user_nm         VARCHAR(100)  NULL,
  access_type_cd  VARCHAR(30)   NOT NULL,
  login_type_cd   VARCHAR(30)   NULL,
  success_yn      CHAR(1)       NOT NULL DEFAULT 'Y',
  request_uri     VARCHAR(500)  NULL,
  http_method     VARCHAR(10)   NULL,
  client_ip       VARCHAR(45)   NULL,
  device_type_cd  VARCHAR(20)   NULL,
  device_os       VARCHAR(80)   NULL,
  device_browser  VARCHAR(80)   NULL,
  device_model    VARCHAR(120)  NULL,
  user_agent      VARCHAR(500)  NULL,
  session_id      VARCHAR(64)   NULL,
  fail_reason     VARCHAR(255)  NULL,
  access_dt       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reg_id          VARCHAR(100)  NOT NULL DEFAULT 'SYSTEM',
  PRIMARY KEY (access_id)
);
CREATE INDEX IF NOT EXISTS idx_user_access_log_user_dt ON user_access_log (user_id, access_dt);
CREATE INDEX IF NOT EXISTS idx_user_access_log_dt ON user_access_log (access_dt);
CREATE INDEX IF NOT EXISTS idx_user_access_log_type ON user_access_log (access_type_cd);
